steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-dev:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-dev:$COMMIT_SHA',
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'liquiz-dev'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-dev:$COMMIT_SHA'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'liquiz-app@liquiz-app.iam.gserviceaccount.com'
      - '--region'
      - 'asia-southeast2'
      - '--cpu'
      - '1'
      - '--memory'
      - '1G'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--set-secrets'
      - 'DATABASE_URL=projects/$PROJECT_ID/secrets/liquiz-dev-database-url/versions/latest'
      - '--set-secrets'
      - 'DIRECT_URL=projects/$PROJECT_ID/secrets/liquiz-dev-direct-url/versions/latest'
      - '--set-secrets'
      - 'NEXTAUTH_URL=projects/$PROJECT_ID/secrets/liquiz-dev-nextauth-url/versions/latest'
      - '--set-secrets'
      - 'NEXTAUTH_SECRET=projects/$PROJECT_ID/secrets/liquiz-dev-nextauth-secret/versions/latest'
      - '--set-secrets'
      - 'GOOGLE_OAUTH_CLIENT_ID=projects/$PROJECT_ID/secrets/liquiz-dev-google-oauth-client-id/versions/latest'
      - '--set-secrets'
      - 'GOOGLE_OAUTH_CLIENT_SECRET=projects/$PROJECT_ID/secrets/liquiz-dev-google-oauth-client-secret/versions/latest'
      - '--set-secrets'
      - 'OPENAI_API_KEY=projects/$PROJECT_ID/secrets/liquiz-dev-openai-api-key/versions/latest'
      - '--set-secrets'
      - 'OPENAI_MODEL_NAME=projects/$PROJECT_ID/secrets/liquiz-dev-openai-model-name/versions/latest'
      - '--set-secrets'
      - 'GCP_SUBJECT_FILE_BUCKET_NAME=projects/$PROJECT_ID/secrets/liquiz-dev-gcp-subject-file-bucket-name/versions/latest'
      - '--set-secrets'
      - 'GCP_PUBSUB_TOPIC_NAME=projects/$PROJECT_ID/secrets/liquiz-dev-gcp-pubsub-topic-name/versions/latest'
      - '--set-secrets'
      - 'GCP_PUBSUB_VERIFICATION_TOKEN=projects/$PROJECT_ID/secrets/liquiz-dev-gcp-pubsub-verification-token/versions/latest'
images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-dev:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
