steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-dev:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-dev:$COMMIT_SHA',
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'liquiz-dev'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-dev:$COMMIT_SHA'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'liquiz-app@liquiz-app.iam.gserviceaccount.com'
      - '--region'
      - 'asia-southeast2'
      - '--cpu'
      - '1'
      - '--memory'
      - '1G'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
    secretEnv:
      [
        'DATABASE_URL',
        'DIRECT_URL',
        'NEXTAUTH_URL',
        'NEXTAUTH_SECRET',
        'GOOGLE_OAUTH_CLIENT_ID',
        'GOOGLE_OAUTH_CLIENT_SECRET',
        'OPENAI_API_KEY',
        'OPENAI_MODEL_NAME',
        'GCP_SUBJECT_FILE_BUCKET_NAME',
        'GCP_PUBSUB_TOPIC_NAME',
        'GCP_PUBSUB_VERIFICATION_TOKEN',
      ]
images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-dev:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-database-url/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-direct-url/versions/latest
      env: 'DIRECT_URL'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-nextauth-url/versions/latest
      env: 'NEXTAUTH_URL'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-nextauth-secret/versions/latest
      env: 'NEXTAUTH_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-google-oauth-client-id/versions/latest
      env: 'GOOGLE_OAUTH_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-google-oauth-client-secret/versions/latest
      env: 'GOOGLE_OAUTH_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-openai-api-key/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-openai-model-name/versions/latest
      env: 'OPENAI_MODEL_NAME'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-gcp-subject-file-bucket-name/versions/latest
      env: 'GCP_SUBJECT_FILE_BUCKET_NAME'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-gcp-pubsub-topic-name/versions/latest
      env: 'GCP_PUBSUB_TOPIC_NAME'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-dev-gcp-pubsub-verification-token/versions/latest
      env: 'GCP_PUBSUB_VERIFICATION_TOKEN'
