steps:
  - name: gcr.io/cloud-builders/docker
    secretEnv:
      [
        'BASE_URL',
        'NEXT_PUBLIC_MAX_FILE_SIZE',
        'NEXT_PUBLIC_MAX_NUMBER_OF_QUESTIONS',
        'NEXT_PUBLIC_MAX_NUMBER_OF_PAGES',
      ]
    entrypoint: bash
    args:
      - '-c'
      - |
      docker build \
      --build-arg="BASE_URL=$$BASE_URL" \
      --build-arg="NEXT_PUBLIC_MAX_FILE_SIZE=$$NEXT_PUBLIC_MAX_FILE_SIZE" \
      --build-arg="NEXT_PUBLIC_MAX_NUMBER_OF_QUESTIONS=$$NEXT_PUBLIC_MAX_NUMBER_OF_QUESTIONS" \
      --build-arg="NEXT_PUBLIC_MAX_NUMBER_OF_PAGES=$$NEXT_PUBLIC_MAX_NUMBER_OF_PAGES" \
      -t asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-production:$COMMIT_SHA .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-production:$COMMIT_SHA',
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'liquiz-production'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-production:$COMMIT_SHA'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'liquiz-app@liquiz-app.iam.gserviceaccount.com'
      - '--region'
      - 'asia-southeast2'
      - '--cpu'
      - '1'
      - '--memory'
      - '1G'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--timeout'
      - '600'
      - '--set-secrets'
      - 'BASE_URL=liquiz-production-base-url:latest'
      - '--set-secrets'
      - 'DATABASE_URL=liquiz-production-database-url:latest'
      - '--set-secrets'
      - 'DIRECT_URL=liquiz-production-direct-url:latest'
      - '--set-secrets'
      - 'NEXTAUTH_URL=liquiz-production-nextauth-url:latest'
      - '--set-secrets'
      - 'NEXTAUTH_SECRET=liquiz-production-nextauth-secret:latest'
      - '--set-secrets'
      - 'GOOGLE_OAUTH_CLIENT_ID=liquiz-production-google-oauth-client-id:latest'
      - '--set-secrets'
      - 'GOOGLE_OAUTH_CLIENT_SECRET=liquiz-production-google-oauth-client-secret:latest'
      - '--set-secrets'
      - 'OPENAI_API_KEY=liquiz-production-openai-api-key:latest'
      - '--set-secrets'
      - 'OPENAI_MODEL_NAME=liquiz-production-openai-model-name:latest'
      - '--set-secrets'
      - 'GCP_SUBJECT_FILE_BUCKET_NAME=liquiz-production-gcp-subject-file-bucket-name:latest'
      - '--set-secrets'
      - 'GCP_PUBSUB_VERIFICATION_TOKEN=liquiz-production-gcp-pubsub-verification-token:latest'
      - '--set-secrets'
      - 'GCP_PUBSUB_TOPIC_NAME=liquiz-production-gcp-pubsub-topic-name:latest'
      - '--set-secrets'
      - 'GCP_PUBSUB_HISTORY_SUMMARY_TOPIC_NAME=liquiz-production-gcp-pubsub-history-summary-topic-name:latest'
images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/liquiz/liquiz-production:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/liquiz-production-base-url/versions/latest
      env: 'BASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-production-max-file-size/versions/latest
      env: 'NEXT_PUBLIC_MAX_FILE_SIZE'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-production-max-number-of-questions/versions/latest
      env: 'NEXT_PUBLIC_MAX_NUMBER_OF_QUESTIONS'
    - versionName: projects/$PROJECT_ID/secrets/liquiz-production-max-number-of-pages/versions/latest
      env: 'NEXT_PUBLIC_MAX_NUMBER_OF_PAGES'
