import {
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BookIcon,
  BookmarkIcon,
  BookmarkPlusIcon,
  BookPlusIcon,
  CheckIcon,
  ChevronRightIcon,
  DropletsIcon,
  ExternalLinkIcon,
  FileIcon,
  HistoryIcon,
  InfoIcon,
  Loader2Icon,
  MenuIcon,
  PlusIcon,
  SearchIcon,
  ShieldXIcon,
  StarIcon,
  TargetIcon,
  Trash2Icon,
  XIcon,
} from 'lucide-react';

export const Icons = {
  Brand: DropletsIcon,
  Search: SearchIcon,
  Cancel: XIcon,
  Loader: Loader2Icon,
  Menu: MenuIcon,
  Subject: BookIcon,
  Topic: BookmarkIcon,
  Favorite: StarIcon,
  BackToTop: ArrowUpIcon,
  Error: ShieldXIcon,
  ChevronRight: ChevronRightIcon,
  AddSubject: BookPlusIcon,
  History: HistoryIcon,
  Plus: PlusIcon,
  Back: ArrowLeftIcon,
  File: FileIcon,
  ExternalLink: ExternalLinkIcon,
  AddTopic: BookmarkPlusIcon,
  Retake: TargetIcon,
  Correct: CheckIcon,
  Incorrect: XIcon,
  Next: ArrowRightIcon,
  Info: InfoIcon,
  Delete: Trash2Icon,
};
